name: sudoku_solver_generator
description: A library to generate and/or solve Sudoku puzzles.
version: 1.0.0+1
homepage: https://github.com/VarunS2002/Dart-sudoku_solver_generator

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
